### ISSUE TITLE
redstat.h is incompatible with Posix 2008 OS.

### ISSUE THREAD

**Issue by jcdubois** [datalightinc/reliance-edge#3]
If an OS is Posix 2008 compliant (for example linux) it should have the following define in its stat.h file:

\# define st_atime st_atim.tv_sec

Same thing for st_mtime and st_ctime.

This "define" is to allow backward compatibility for source code that would still use st_atime (or st_mtime or st_ctime)

As a result any file including (directly or indirectly) both the POSIX compliant stat.h and redstat.h will fail to compile.

The reported error is not really clear on the issue, but it all come from the above define as st_atime is expanded to st_atim.tv_sec.

../../../include/redstat.h:70:17: error: expected ‘:’, ‘,’, ‘;’, ‘}’ or ‘__attribute__’ before ‘.’ token
     uint32_t    st_atime;   /**< Time of last access (seconds since 01-01-1970). */
                 ^

**Comment by aamcampbell** [comment]
Thanks for reporting this! We have bumped into this issue as well. The good thing is that the collision between <sys/stat.h> and <redstat.h> is only likely to occur in development tools that simultaneously use a POSIX-compliant VFS and the Reliance Edge POSIX-like API. And there is a simple workaround:

    #include <sys/types.h>
    #include <sys/stat.h>

    #undef st_atime
    #undef st_mtime
    #undef st_ctime

    #include <redfs.h>
    #include <redposix.h>

But we recognize that this is somewhat clumsy. It leaves us with a decision:

1. We could use the POSIX 2008 `struct timespec` fields for timestamps. This would be the ideal for modern, fully POSIX compliant platforms such as Linux. However, the `struct timespec` field uses nanosecond granularity, which seems unrealistic for the target ecosystem of Reliance Edge (IoT/microcontrollers).
2. We could use custom names for the timestamp fields, e.g. `RedStATime`. This would avoid any symbol collision, but clearly deviates from the POSIX interface we are trying to implement.
3. Or we could stick with the POSIX 2004 `time_t` timestamp fields, which best fit the needs of the target ecosystem, even though this adds some difficulty on Linux.

We chose option (3), doing our best to benefit the IoT developers that write applications on RTOS's such as FreeRTOS, MQX, or ARM mbed. We mention this as a deviation from modern POSIX in the "Differences from POSIX" section of the Reliance Edge Developer's Guide.
