### ISSUE TITLE
Failing to compile linux host tools.

### ISSUE THREAD

**Issue by jcdubois** [datalightinc/reliance-edge#4]
Compilation is failing with the foolowing:

gcc -Wall -Werror   -I ../../../projects/linux/host -I ../../../include -I ../../../core/include -I ../../../os/linux/include -DD_DEBUG=0 -D_XOPEN_SOURCE=500 -x c -c ../../../tools/getopt.c -o ../../../tools/getopt.to
../../../tools/getopt.c:102:19: error: ‘illoptchar’ defined but not used [-Werror=unused-const-variable=]
 static const char illoptchar[] = "illegal option -- %c\n"; /* From P1003.2 */
                   ^~~~~~~~~~
cc1: all warnings being treated as errors
../../../os/linux/build/host.mk:23 : la recette pour la cible « ../../../tools/getopt.to » a échouée
make: *** [../../../tools/getopt.to] Erreur 1

Please find proposed patch in attached file.

JC

[Linux-Allow-linux-to-compile.txt](https://github.com/datalightinc/reliance-edge/files/613793/Linux-Allow-linux-to-compile.txt)

**Comment by aamcampbell** [comment]
Good catch. I will make sure this is fixed in the next build.

I am surprised that GCC ignores this on my machine, tested with GCC 4.6, 4.8, and 5.4. Out of curiosity, which version of GCC are you using?

**Comment by jcdubois** [comment]
I have gcc 6.2.0 on Ubuntu 16.10.

JC

**Comment by jcdubois** [comment]
For the record, I am also compiling with clang (3.8.1).

JC

**Comment by aamcampbell** [comment]
This issue has been resolved with commit f743cac.
